[project]
authors = ["Ivan Donadello <ivan.donadello@unibz.it>", "Francesco Riva <francesco.riva@unibz.it>", "Fabrizio Maria Maggi <maggi@inf.unibz.it>", "Sergio Tessaris <tessaris@inf.unibz.it>"]
channels = ["conda-forge"]
description = "Python library to perform discovery, conformance checking and query checking of DECLARE constraints."
name = "ASP-based log generation"
platforms = ["osx-64", "osx-arm64", "linux-64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]
lab = { description = "starts Jupyter Lab in the current directory", cmd = ["jupyter","lab", "--notebook-dir=$INIT_CWD"]}
nbconvert = {description = "convert the provided notebook to html in the './output/' directory", cmd = [
    "cd", "$INIT_CWD", ";",
    "jupyter", "nbconvert", "--to=html",
    "--ExecutePreprocessor.timeout=-1", "--execute",
    "--output={notebook_name}_$(date -u +'%Y-%m-%dT%H%M%SZ_')$(git describe --dirty 2>/dev/null)",
    "--output-dir=$INIT_CWD/output"] }
experiments = { description = "runs the experiments defined in the justfile", cmd = [
    "cd", "$INIT_CWD", ";",
    "just", "experiments"] }

[dependencies]
packaging = "*"
mlxtend = ">=0.20.0"
clingo = ">=5.7.1,<6"
"boolean.py" = "*"
pandas = ">=1.3.4"

cvxopt = "*"
jupyterlab = ">=4.3.3,<5"
pixi-kernel = ">=0.5.1,<0.6"
levenshtein = ">=0.26.1,<0.27"
papermill = ">=2.6.0,<3"
just = ">=1.41.0,<2"

[pypi-dependencies]
logaut = "*"
pm4py = ">=2.5.1"
ltlf2dfa = "==1.0.2"

declare4py = { path = ".", editable = true}
