[project]
authors = ["Ivan Donadello <ivan.donadello@unibz.it>", "Francesco Riva <francesco.riva@unibz.it>", "Fabrizio Maria Maggi <maggi@inf.unibz.it>", "Sergio Tessaris <tessaris@inf.unibz.it>"]
channels = ["conda-forge"]
description = "Python library to perform discovery, conformance checking and query checking of DECLARE constraints."
name = "ASP-based log generation"
platforms = ["osx-64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
packaging = "*"
mlxtend = ">=0.20.0"
clingo = ">=5.6.2"
"boolean.py" = "*"
pandas = ">=1.3.4"

cvxopt = "*"
jupyterlab = ">=4.3.1,<5"
pixi-kernel = ">=0.5.1,<0.6"
levenshtein = ">=0.26.1,<0.27"

[pypi-dependencies]
logaut = "*"
pm4py = ">=2.5.1"
ltlf2dfa = "==1.0.2"

declare4py = { path = ".", editable = true}
